---
Name: silverstripe-discoverer-search-ui
---
SilverStripe\Core\Manifest\ModuleManifest:
  module_priority:
    - 'silverstripe/silverstripe-discoverer-search-ui'
    - 'silverstripe/silverstripe-discoverer'
